language: ruby
sudo: false
cache: bundler
rvm:
  # Still not in Travis :(
  # - 2.1.9
  - 2.2.0
  - 2.2.1
  - 2.2.2
  - 2.2.3
  - 2.2.4
  - 2.3.0
  - 2.3.1
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
script: bundle exec rspec
notifications:
  email:
    - team@wpscan.org
# do not build gh-pages branch
branches:
  except:
    - gh-pages
