name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [2.4, 2.5, 2.6, 2.7]

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Set up Ruby ${{ matrix.ruby }}
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: Restore GEM cache
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-${{ matrix.ruby }}-gem-${{ hashFiles('**/wpscan.gemspec') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ruby }}-gem-

    - name: Install GEMs
      run: |
        gem install bundler
        bundle config force_ruby_platform true
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: rspec
      run: |
        bundle exec rspec

    - name: rubocop
      run: |
        bundle exec rubocop

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
